name: wal-g
on:
  push:
    tags:
      - "v*"

jobs:
  release-debian:
    name: Release Debian
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      OUTPUT_NAME: wal-g-pg-debian-11-aarch64
    steps:
      - uses: actions/checkout@v4
        with:
          repository: wal-g/wal-g
          ref: ${{ github.ref }}

      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: bullseye
          env: | # YAML, but pipe character is necessary
            USE_LIBSODIUM: 1
            USE_LZO: 1

          shell: /bin/bash
          run: |
            echo "deb http://deb.debian.org/debian bullseye-backports main" >> /etc/apt/sources.list.d/bullseye-backports.list
            apt-get update
            apt-get install -y build-essential curl git cmake golang-1.18 liblzo2-dev brotli libsodium-dev

            export PATH="/usr/lib/go-1.18/bin:$PATH"

            go get -v -t -d ./...
            make deps
            make pg_build

      - run: mv main/pg/wal-g ${{ env.OUTPUT_NAME }}
      - run: sha256sum ${{ env.OUTPUT_NAME }} > ${{ env.OUTPUT_NAME }}.sha256
      - uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.BOT_PAT }}
          files: |
            ${{ env.OUTPUT_NAME }}
            ${{ env.OUTPUT_NAME }}.sha256
